version: "3.5"

services:
    api:
        build:
            context: .
        restart: unless-stopped
        environment:
            - PORT=${BEAUF_NET_PORT}
            - SECRET=${BEAUF_NET_SECRET}
            - SALT_ROUNDS=${BEAUF_NET_SALT_ROUNDS}
            - POSTGRES_HOST=${BEAUF_NET_POSTGRES_HOST}
            - POSTGRES_DB=${BEAUF_NET_POSTGRES_DB}
            - POSTGRES_USERNAME=${BEAUF_NET_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${BEAUF_NET_POSTGRES_PASSWORD}
            - POSTGRES_PORT=${BEAUF_NET_POSTGRES_PORT}
        ports:
            - "${BEAUF_NET_PORT}:5000"
        volumes:
            - ./src:/usr/src/app/src
        depends_on:
            - "db"

    db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${BEAUF_NET_POSTGRES_DB}
            - POSTGRES_USER=${BEAUF_NET_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${BEAUF_NET_POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        command: -p ${BEAUF_NET_POSTGRES_PORT}

volumes:
    db-data:
        driver: local
    redis-data:
        driver: local
