version: "3.5"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        environment:
            - PORT=${BEAUF_NET_PORT}
            - SECRET=${BEAUF_NET_SECRET}
            - POSTGRES_HOST=${BEAUF_NET_POSTGRES_HOST}
            - POSTGRES_DB=${BEAUF_NET_POSTGRES_DB}
            - POSTGRES_USERNAME=${BEAUF_NET_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${BEAUF_NET_POSTGRES_PASSWORD}
            - POSTGRES_PORT=${BEAUF_NET_POSTGRES_PORT}
            - ADMIN_USERNAME=${BEAUF_NET_ADMIN_USERNAME}
            - ADMIN_PASSWORD=${BEAUF_NET_ADMIN_PASSWORD}
            - ADMIN_EMAIL=${BEAUF_NET_ADMIN_EMAIL}
            - CAPTCHA_SECRET_KEY=${BEAUF_NET_CAPTCHA_SECRET}
            - MAIL_HOST=${BEAUF_NET_MAIL_HOST}
            - MAIL_PORT=${BEAUF_NET_MAIL_PORT}
            - MAIL_USER=${BEAUF_NET_MAIL_USER}
            - MAIL_PASS=${BEAUF_NET_MAIL_PASS}
            - BASE_URL=${BEAUF_NET_BASE_URL}
        ports:
            - "${BEAUF_NET_PORT}:5000"
        volumes:
            - ./src:/usr/src/app/src
        depends_on:
            - "db"

    db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${BEAUF_NET_POSTGRES_DB}
            - POSTGRES_USER=${BEAUF_NET_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${BEAUF_NET_POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        command: -p ${BEAUF_NET_POSTGRES_PORT}

    adminer:
        image: adminer:latest
        depends_on:
            - db
        ports:
            - 8080:8080

volumes:
    db-data:
        driver: local
