apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: beauf-net
  labels:
    app: postgres
type: opaque
data:
  POSTGRES_DB: "{{ postgres_db | b64encode | regex_replace('\n', '') }}"
  POSTGRES_USER: "{{ postgres_user | b64encode | regex_replace('\n', '') }}"
  POSTGRES_PASSWORD: "{{ postgres_pass | b64encode | regex_replace('\n', '') }}"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: beauf-net
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /var/beauf-net/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ storage_hostname }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: beauf-net
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-storage"
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: beauf-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          image: postgres:10-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: beauf-net
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
